# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)

tensor([[0.8464, 0.0891, 0.0743, 0.5834, 0.2859, 0.7610, 0.0641],
        [0.4562, 0.3367, 0.9342, 0.8983, 0.6533, 0.8893, 0.5817],
        [0.6219, 0.6683, 0.4039, 0.3309, 0.0669, 0.9745, 0.5843],
        [0.7627, 0.3354, 0.8490, 0.3607, 0.7142, 0.1134, 0.2614],
        [0.2204, 0.6473, 0.5365, 0.5022, 0.1571, 0.8000, 0.0379],
        [0.1687, 0.5905, 0.1027, 0.4813, 0.1817, 0.3850, 0.5294],
        [0.8588, 0.0105, 0.2156, 0.0763, 0.3044, 0.0340, 0.9456]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
x = torch.rand(7,7)
y = torch.rand(1,7)
y = torch.transpose(y, 0, 1)
# Perform matrix multiplication
torch.matmul(x, y)

tensor([[2.1758],
        [2.7494],
        [1.8747],
        [2.3964],
        [2.2742],
        [1.5315],
        [1.5614]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(7,1)
# Matrix multiply tensors
torch.matmul(x, y)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
x = torch.rand(2,3).to('cuda')
y = torch.rand(2,3).to('cuda')
x, y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [37]:
# Perform matmul on tensor_A and tensor_B
y = torch.transpose(y, 0, 1)
z = torch.matmul(x, y)

### 8. Find the maximum and minimum values of the output of 7.

In [40]:
# Find max
print(torch.max(z))
# Find min
print(torch.min(z))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [41]:
# Find arg max
print(torch.argmax(z))

# Find arg min
print(torch.argmin(z))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [46]:
# Set seed
seed = 7
torch.manual_seed(seed)
# Create random tensor
x = torch.rand(1, 1, 1, 10)
print(x, x.shape)
# Remove single dimensions
x = torch.squeeze(x)
print(x,x.shape)
# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
